[[GAP_pkg_zeromqinterface]]
arch = "aarch64"
git-tree-sha1 = "6b14eba63d8fd85a9d0d69eb871464a8a6c838b2"
os = "macos"

    [[GAP_pkg_zeromqinterface.download]]
    sha256 = "09dc56646364ab3307fe48512349bf1edb4ae605fa264085abccbceae0db318f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_zeromqinterface_jll.jl/releases/download/GAP_pkg_zeromqinterface-v0.1600.2+0/GAP_pkg_zeromqinterface.v0.1600.2.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_zeromqinterface]]
arch = "aarch64"
git-tree-sha1 = "c131542d0b243033fb2f2fef6912fb780b56d6f4"
libc = "glibc"
os = "linux"

    [[GAP_pkg_zeromqinterface.download]]
    sha256 = "be931153a8432cb62e4a61bf5620eca5330e5dbe32900c93688c78a9f0a5c4a1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_zeromqinterface_jll.jl/releases/download/GAP_pkg_zeromqinterface-v0.1600.2+0/GAP_pkg_zeromqinterface.v0.1600.2.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_zeromqinterface]]
arch = "aarch64"
git-tree-sha1 = "8e9abe051c251002809229dc5ab8daa8dc04488b"
libc = "musl"
os = "linux"

    [[GAP_pkg_zeromqinterface.download]]
    sha256 = "8d52c152b91fb55c2aa5ac1f8e532aa35d2a7f95ccece63442f70b09eed643a4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_zeromqinterface_jll.jl/releases/download/GAP_pkg_zeromqinterface-v0.1600.2+0/GAP_pkg_zeromqinterface.v0.1600.2.aarch64-linux-musl.tar.gz"
[[GAP_pkg_zeromqinterface]]
arch = "aarch64"
git-tree-sha1 = "3696db28ecc839d88bdf0bf446b1d8a49822b458"
os = "freebsd"

    [[GAP_pkg_zeromqinterface.download]]
    sha256 = "d5c31adf1ee582cf72ecd0c5cce0a068a49278eeab03721401fe49650c70d58f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_zeromqinterface_jll.jl/releases/download/GAP_pkg_zeromqinterface-v0.1600.2+0/GAP_pkg_zeromqinterface.v0.1600.2.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_zeromqinterface]]
arch = "powerpc64le"
git-tree-sha1 = "466c1788772c8a672642538cf2446eb78dfb91bd"
libc = "glibc"
os = "linux"

    [[GAP_pkg_zeromqinterface.download]]
    sha256 = "d232cc0eb3018d6b03d44f22c432d1173b18b68ddf3ced2ddd54e25f302623c5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_zeromqinterface_jll.jl/releases/download/GAP_pkg_zeromqinterface-v0.1600.2+0/GAP_pkg_zeromqinterface.v0.1600.2.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_zeromqinterface]]
arch = "riscv64"
git-tree-sha1 = "47d910172003b7f7a96207c0d27a5d6562a49d36"
libc = "glibc"
os = "linux"

    [[GAP_pkg_zeromqinterface.download]]
    sha256 = "0fd289cc6a3aabff3b69c1c82b6936d4d23e8c11710ff4b111924aa0d3034652"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_zeromqinterface_jll.jl/releases/download/GAP_pkg_zeromqinterface-v0.1600.2+0/GAP_pkg_zeromqinterface.v0.1600.2.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_zeromqinterface]]
arch = "x86_64"
git-tree-sha1 = "31e5d4876919dae6ac35e8fd29f8c8a549b5ef3d"
os = "macos"

    [[GAP_pkg_zeromqinterface.download]]
    sha256 = "894b0f8e6d01ab769ff2ddf32bf5b50a72172ce816e7647d6d0328fb30e8315b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_zeromqinterface_jll.jl/releases/download/GAP_pkg_zeromqinterface-v0.1600.2+0/GAP_pkg_zeromqinterface.v0.1600.2.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_zeromqinterface]]
arch = "x86_64"
git-tree-sha1 = "4300a54e533f9b815a6136c1727a12abe55933dd"
libc = "glibc"
os = "linux"

    [[GAP_pkg_zeromqinterface.download]]
    sha256 = "2e0a2cb50012d3ddffcd48976bda5f87394095b3aeed555be62cdfac629a4f8e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_zeromqinterface_jll.jl/releases/download/GAP_pkg_zeromqinterface-v0.1600.2+0/GAP_pkg_zeromqinterface.v0.1600.2.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_zeromqinterface]]
arch = "x86_64"
git-tree-sha1 = "124ed642e9257ab56b8031c74936ba9077451168"
libc = "musl"
os = "linux"

    [[GAP_pkg_zeromqinterface.download]]
    sha256 = "0670e5869b5f4f1530f7ce0d7c1e088dc9a705872c92a9d969999c8372a6c5be"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_zeromqinterface_jll.jl/releases/download/GAP_pkg_zeromqinterface-v0.1600.2+0/GAP_pkg_zeromqinterface.v0.1600.2.x86_64-linux-musl.tar.gz"
[[GAP_pkg_zeromqinterface]]
arch = "x86_64"
git-tree-sha1 = "075b26f24d43e05cb4034075a827864f39c481c4"
os = "freebsd"

    [[GAP_pkg_zeromqinterface.download]]
    sha256 = "52cf345fbe430571500fe14daa012059ac86254c62b0956b30cd1077c89f69b9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_zeromqinterface_jll.jl/releases/download/GAP_pkg_zeromqinterface-v0.1600.2+0/GAP_pkg_zeromqinterface.v0.1600.2.x86_64-unknown-freebsd.tar.gz"
